version: '3.8'

services:
  web:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

  db:
    image: mysql
    container_name: mysql-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_HOST: '${MYSQL_ROOT_HOST}'
      MYSQL_DATABASE: weather
    volumes:
      - my-db:/var/lib/mysql

volumes:
  grafana-data:
  my-db:
